In [ ]:
import pandas as pd
df = pd.ExcelFile('gesamtdatei_stundenwerte.xlsx')
df = pd.read_excel(df, 'Jahresdatei 2021')
df = pd.DataFrame(df)
df

In [13]:
df['Datetime']= pd.to_datetime(df['Date']+' '+df['Time'])
df.drop(['Date', 'Time'], axis=1, inplace= True)
df.set_index('Datetime', inplace= True)
print(df.resample('H').sum(min_count=1))

# output
                       Value
Datetime                    
2021-11-06 04:00:00  12637.1
2021-11-06 05:00:00  10859.4
2021-11-06 06:00:00      NaN
2021-11-06 07:00:00   1111.1

,ZÃ¤hlstelle Inbetriebnahme,02-MI-JAN-N 01.04.2015,02-MI-JAN-S 01.04.2015,03-MI-SAN-O 01.06.2015,03-MI-SAN-W 01.06.2015,05-FK-OBB-O 01.06.2015,05-FK-OBB-W 01.06.2015,06-FK-FRA-O 01.06.2016,06-FK-FRA-W 01.06.2016,10-PA-BER-N 01.05.2016,...,20-TS-MAR-N 01.05.2016,20-TS-MAR-S 01.05.2016,21-NK-MAY 01.05.2016,23-TK-KAI 01.05.2016,24-MH-ALB 01.07.2015,26-LI-PUP 01.06.2015,27-RE-MAR 01.05.2015,06-CW-JU-O 27.07.2021,06-CW-JU-W 27.07.2021,02-MI-AL-W 16.12.2021
0,2021-01-01 00:00:00,5.0,6.0,4.0,2.0,NaN,NaN,8.0,5.0,5.0,...,0.0,2.0,29.0,6.0,4.0,15.0,6.0,NaN,NaN,NaN
1,2021-01-01 01:00:00,21.0,14.0,12.0,18.0,NaN,NaN,24.0,7.0,23.0,...,2.0,0.0,51.0,7.0,13.0,21.0,4.0,NaN,NaN,NaN
2,2021-01-01 02:00:00,28.0,37.0,13.0,17.0,NaN,NaN,26.0,23.0,24.0,...,1.0,1.0,51.0,6.0,5.0,25.0,11.0,NaN,NaN,NaN
3,2021-01-01 03:00:00,36.0,27.0,10.0,14.0,NaN,NaN,24.0,18.0,20.0,...,1.0,3.0,41.0,5.0,3.0,18.0,9.0,NaN,NaN,NaN
4,2021-01-01 04:00:00,24.0,24.0,5.0,8.0,NaN,NaN,12.0,14.0,19.0,...,1.0,3.0,30.0,6.0,4.0,15.0,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2021-12-31 19:00:00,32.0,27.0,21.0,29.0,NaN,NaN,3.0,29.0,19.0,...,0.0,4.0,74.0,4.0,10.0,17.0,14.0,13.0,18.0,22.0
8756,2021-12-31 20:00:00,17.0,21.0,14.0,14.0,NaN,NaN,2.0,10.0,13.0,...,0.0,3.0,56.0,15.0,1.0,13.0,13.0,7.0,8.0,8.0
8757,2021-12-31 21:00:00,13.0,23.0,15.0,15.0,NaN,NaN,2.0,8.0,14.0,...,0.0,1.0,26.0,7.0,4.0,4.0,6.0,2.0,8.0,20.0
8758,2021-12-31 22:00:00,25.0,15.0,8.0,11.0,NaN,NaN,2.0,13.0,7.0,...,0.0,1.0,19.0,6.0,2.0,5.0,9.0,5.0,9.0,9.0
8759,2021-12-31 23:00:00,10.0,17.0,10.0,11.0,NaN,NaN,3.0,13.0,6.0,...,0.0,1.0,22.0,3.0,0.0,12.0,4.0,13.0,5.0,9.0